# Generated by Django 3.2.4 on 2021-06-15 00:19

import colleges.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=700, unique=True)),
                ('name', models.CharField(max_length=700)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, upload_to=colleges.models.save_course_image, verbose_name='Course Image')),
                ('description', models.TextField(blank=True, max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=700, unique=True)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_id', models.CharField(max_length=700, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=700)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Chapter no')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to=colleges.models.save_lesson_files, verbose_name='Video')),
                ('ppt', models.FileField(blank=True, null=True, upload_to=colleges.models.save_lesson_files, verbose_name='Presentation')),
                ('Note', models.FileField(blank=True, null=True, upload_to=colleges.models.save_lesson_files, verbose_name='Note')),
                ('Standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.standard')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson', to='colleges.courses')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='standard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='colleges.standard'),
        ),
    ]
