# Generated by Django 3.2.4 on 2021-06-12 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import school.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(blank=True, max_length=700)),
                ('profile_pic', models.ImageField(blank=True, upload_to=school.models.path_and_rename, verbose_name='profile_picture')),
                ('user_type', models.CharField(choices=[('student', 'student'), ('parent', 'parent'), ('teacher', 'teacher')], default='student', max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
